import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, ChevronDown, ChevronUp, Loader2, Plus, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Switch } from "@/components/ui/switch";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

const money = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value);
const statusLabel = { aguardando_aprovacao: "Aguardando aprovação", aprovado: "Aprovado", recusado: "Recusado", cancelado: "Cancelado" } as const;

export default function AdminB2B() {
  const queryClient = useQueryClient();
  const [termOpen, setTermOpen] = useState(false);
  const [termName, setTermName] = useState("");
  const [termDescription, setTermDescription] = useState("");
  const [termDays, setTermDays] = useState("");
  const [expandedOrder, setExpandedOrder] = useState<string | null>(null);
  const [representativeOpen, setRepresentativeOpen] = useState(false);
  const [repEmail, setRepEmail] = useState("");
  const [repCompany, setRepCompany] = useState("");
  const [repDocument, setRepDocument] = useState("");
  const [repPhone, setRepPhone] = useState("");

  const { data: accounts = [], isLoading: accountsLoading } = useQuery({ queryKey: ["admin-b2b-accounts"], queryFn: async () => { const { data, error } = await supabase.from("b2b_accounts").select("*").eq("account_type", "representante").order("created_at", { ascending: false }); if (error) throw error; return data; } });
  const { data: clients = [] } = useQuery({ queryKey: ["admin-b2b-clients"], queryFn: async () => { const { data, error } = await supabase.from("b2b_clients").select("*"); if (error) throw error; return data; } });
  const { data: terms = [], isLoading: termsLoading } = useQuery({ queryKey: ["admin-b2b-terms"], queryFn: async () => { const { data, error } = await supabase.from("b2b_payment_terms").select("*").order("created_at", { ascending: false }); if (error) throw error; return data; } });
  const { data: orders = [], isLoading: ordersLoading } = useQuery({ queryKey: ["admin-b2b-orders"], queryFn: async () => { const { data, error } = await supabase.from("b2b_orders").select("*").order("created_at", { ascending: false }); if (error) throw error; return data; } });
  const { data: items = [] } = useQuery({ queryKey: ["admin-b2b-items", orders.map((o) => o.id).join(",")], enabled: orders.length > 0, queryFn: async () => { const { data, error } = await supabase.from("b2b_order_items").select("*").in("order_id", orders.map((o) => o.id)); if (error) throw error; return data; } });

  const updateAccount = useMutation({ mutationFn: async ({ id, status }: { id: string; status: "aprovado" | "recusado" }) => { const { error } = await supabase.from("b2b_accounts").update({ status }).eq("id", id); if (error) throw error; }, onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ["admin-b2b-accounts"] }); toast.success("Acesso atualizado."); }, onError: (e: Error) => toast.error(e.message) });
  const createRepresentative = useMutation({ mutationFn: async () => { const { error } = await supabase.rpc("admin_create_b2b_representative", { _email: repEmail.trim(), _company_name: repCompany.trim(), _document: repDocument.trim() || undefined, _phone: repPhone.trim() || undefined }); if (error) throw error; }, onSuccess: () => { setRepresentativeOpen(false); setRepEmail(""); setRepCompany(""); setRepDocument(""); setRepPhone(""); void queryClient.invalidateQueries({ queryKey: ["admin-b2b-accounts"] }); toast.success("Representante cadastrado e aprovado."); }, onError: (e: Error) => toast.error(e.message) });
  const createTerm = useMutation({ mutationFn: async () => { const days = termDays.split(/[;,/\s]+/).filter(Boolean).map(Number); if (!termName.trim() || days.some((day) => !Number.isInteger(day) || day < 0)) throw new Error("Informe um nome e dias válidos."); const { error } = await supabase.from("b2b_payment_terms").insert({ name: termName.trim(), description: termDescription.trim() || null, installment_days: days }); if (error) throw error; }, onSuccess: () => { setTermOpen(false); setTermName(""); setTermDescription(""); setTermDays(""); void queryClient.invalidateQueries({ queryKey: ["admin-b2b-terms"] }); toast.success("Condição criada."); }, onError: (e: Error) => toast.error(e.message) });
  const toggleTerm = useMutation({ mutationFn: async ({ id, active }: { id: string; active: boolean }) => { const { error } = await supabase.from("b2b_payment_terms").update({ active }).eq("id", id); if (error) throw error; }, onSuccess: () => void queryClient.invalidateQueries({ queryKey: ["admin-b2b-terms"] }), onError: (e: Error) => toast.error(e.message) });
  const reviewOrder = useMutation({ mutationFn: async ({ id, approve }: { id: string; approve: boolean }) => { const { error } = await supabase.rpc("review_b2b_order", { _order_id: id, _approve: approve }); if (error) throw error; }, onSuccess: (_, variables) => { void queryClient.invalidateQueries({ queryKey: ["admin-b2b-orders"] }); void queryClient.invalidateQueries({ queryKey: ["admin-products"] }); toast.success(variables.approve ? "Pedido aprovado e estoque reservado." : "Pedido recusado."); }, onError: (e: Error) => toast.error(e.message) });

  const accountName = (id: string) => accounts.find((a) => a.id === id)?.company_name || accounts.find((a) => a.id === id)?.email || "Representante";
  const clientName = (id: string) => clients.find((c) => c.id === id)?.company_name || "Cliente";

  return <div className="space-y-6"><div><h1 className="text-3xl font-bold">Comercial B2B</h1><p className="mt-1 text-sm text-muted-foreground">Representantes, condições comerciais e pedidos para aprovação.</p></div>
    <Tabs defaultValue="pedidos"><TabsList className="grid h-auto w-full grid-cols-3 sm:w-auto sm:inline-grid"><TabsTrigger value="pedidos">Pedidos</TabsTrigger><TabsTrigger value="representantes">Representantes</TabsTrigger><TabsTrigger value="condicoes">Condições</TabsTrigger></TabsList>
      <TabsContent value="pedidos" className="mt-5">{ordersLoading ? <Loader2 className="h-6 w-6 animate-spin" /> : orders.length === 0 ? <p className="border-y py-16 text-center text-muted-foreground">Nenhum pedido B2B.</p> : <div className="divide-y rounded-md border bg-card">{orders.map((order) => { const expanded = expandedOrder === order.id; const orderItems = items.filter((item) => item.order_id === order.id); return <article key={order.id} className="p-5"><button className="flex w-full items-center justify-between gap-4 text-left" onClick={() => setExpandedOrder(expanded ? null : order.id)}><div><p className="font-mono text-xs text-muted-foreground">#{order.id.slice(0,8).toUpperCase()}</p><h2 className="mt-1 font-semibold">{clientName(order.client_id)} <span className="font-normal text-muted-foreground">por {accountName(order.rep_account_id)}</span></h2><p className="mt-1 text-sm text-muted-foreground">{new Date(order.created_at).toLocaleString("pt-BR")} · {order.payment_term_snapshot}</p></div><div className="flex items-center gap-4"><div className="text-right"><Badge variant={order.status === "recusado" ? "destructive" : order.status === "aprovado" ? "default" : "outline"}>{statusLabel[order.status]}</Badge><p className="mt-2 font-semibold">{money(Number(order.total))}</p></div>{expanded ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}</div></button>{expanded && <div className="mt-5 border-t pt-4"><div className="space-y-2">{orderItems.map((item) => <div key={item.id} className="flex justify-between gap-4 text-sm"><span>{item.quantity}× {item.product_name} <span className="text-muted-foreground">({item.product_code || "s/c"})</span></span><span>{money(Number(item.line_total))}</span></div>)}</div>{order.notes && <p className="mt-4 text-sm text-muted-foreground">Observações: {order.notes}</p>}{order.status === "aguardando_aprovacao" && <div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={() => reviewOrder.mutate({ id: order.id, approve: false })} disabled={reviewOrder.isPending}><X className="h-4 w-4" /> Recusar</Button><Button onClick={() => reviewOrder.mutate({ id: order.id, approve: true })} disabled={reviewOrder.isPending}><Check className="h-4 w-4" /> Aprovar e reservar estoque</Button></div>}</div>}</article>; })}</div>}</TabsContent>
      <TabsContent value="representantes" className="mt-5"><div className="mb-4 flex justify-end"><Button onClick={() => setRepresentativeOpen(true)}><Plus className="h-4 w-4" /> Novo representante</Button></div>{accountsLoading ? <Loader2 className="h-6 w-6 animate-spin" /> : accounts.length === 0 ? <p className="border-y py-16 text-center text-muted-foreground">Nenhum representante cadastrado.</p> : <div className="grid gap-4 md:grid-cols-2">{accounts.map((account) => <article key={account.id} className="rounded-md border bg-card p-5"><div className="flex justify-between gap-3"><div><h2 className="font-semibold">{account.company_name || "Representante"}</h2><p className="mt-1 text-sm text-muted-foreground">{account.email || "Sem e-mail"} · {account.document || "Sem documento"}</p></div><Badge variant={account.status === "recusado" ? "destructive" : account.status === "aprovado" ? "default" : "outline"}>{account.status}</Badge></div><div className="mt-5 flex justify-end gap-2"><Button variant="outline" size="sm" onClick={() => updateAccount.mutate({ id: account.id, status: "recusado" })}>Recusar</Button><Button size="sm" onClick={() => updateAccount.mutate({ id: account.id, status: "aprovado" })}>Aprovar</Button></div></article>)}</div>}</TabsContent>
      <TabsContent value="condicoes" className="mt-5"><div className="mb-4 flex justify-end"><Button onClick={() => setTermOpen(true)}><Plus className="h-4 w-4" /> Nova condição</Button></div>{termsLoading ? <Loader2 className="h-6 w-6 animate-spin" /> : <div className="divide-y rounded-md border bg-card">{terms.map((term) => <div key={term.id} className="flex items-center justify-between gap-4 p-5"><div><h2 className="font-semibold">{term.name}</h2><p className="mt-1 text-sm text-muted-foreground">{term.description || (term.installment_days.length ? `Dias: ${term.installment_days.join(" / ")}` : "À vista")}</p></div><div className="flex items-center gap-3"><span className="text-sm text-muted-foreground">{term.active ? "Ativa" : "Inativa"}</span><Switch checked={term.active} onCheckedChange={(active) => toggleTerm.mutate({ id: term.id, active })} /></div></div>)}</div>}</TabsContent>
    </Tabs>
    <Dialog open={termOpen} onOpenChange={setTermOpen}><DialogContent><DialogHeader><DialogTitle>Nova condição de pagamento</DialogTitle></DialogHeader><form onSubmit={(e) => { e.preventDefault(); createTerm.mutate(); }} className="space-y-4"><div className="space-y-2"><Label>Nome *</Label><Input value={termName} onChange={(e) => setTermName(e.target.value)} placeholder="Ex.: 30/60/90 dias" required /></div><div className="space-y-2"><Label>Dias das parcelas</Label><Input value={termDays} onChange={(e) => setTermDays(e.target.value)} placeholder="30, 60, 90" /></div><div className="space-y-2"><Label>Descrição</Label><Textarea value={termDescription} onChange={(e) => setTermDescription(e.target.value)} /></div><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setTermOpen(false)}>Cancelar</Button><Button type="submit" disabled={createTerm.isPending}>Salvar</Button></div></form></DialogContent></Dialog>
    <Dialog open={representativeOpen} onOpenChange={setRepresentativeOpen}><DialogContent><DialogHeader><DialogTitle>Novo representante</DialogTitle></DialogHeader><form onSubmit={(e) => { e.preventDefault(); createRepresentative.mutate(); }} className="space-y-4"><p className="text-sm text-muted-foreground">O representante precisa ter criado uma conta na loja com este mesmo e-mail.</p><div className="space-y-2"><Label>E-mail da conta *</Label><Input type="email" value={repEmail} onChange={(e) => setRepEmail(e.target.value)} required /></div><div className="space-y-2"><Label>Nome ou empresa *</Label><Input value={repCompany} onChange={(e) => setRepCompany(e.target.value)} required /></div><div className="grid grid-cols-2 gap-4"><div className="space-y-2"><Label>Documento</Label><Input value={repDocument} onChange={(e) => setRepDocument(e.target.value)} /></div><div className="space-y-2"><Label>Telefone</Label><Input value={repPhone} onChange={(e) => setRepPhone(e.target.value)} /></div></div><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setRepresentativeOpen(false)}>Cancelar</Button><Button type="submit" disabled={createRepresentative.isPending}>{createRepresentative.isPending && <Loader2 className="h-4 w-4 animate-spin" />} Cadastrar e aprovar</Button></div></form></DialogContent></Dialog>
  </div>;
}